services:
  service-registry:
    image: wilbax/service-registry:latest
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - private-network
      - public-network
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    image: wilbax/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - public-network
      - private-network
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - service-registry

  user-management-service:
    image: wilbax/user-management:latest
    container_name: user-management-service
    networks:
      - private-network
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
      - AWS_ACCESS=${AWS_ACCESS}
      - AWS_SECRET=${AWS_SECRET}
      - AWS_ACCOUNT_NO=${AWS_ACCOUNT_NO}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
    env_file:
      - .env
    depends_on:
      - service-registry

  product-management-service:
    image: wilbax/product-management:latest
    container_name: product-management-service
    networks:
      - private-network
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
      - AWS_ACCESS=${AWS_ACCESS}
      - AWS_SECRET=${AWS_SECRET}
      - AWS_ACCOUNT_NO=${AWS_ACCOUNT_NO}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
    env_file:
      - .env
    depends_on:
      - service-registry

  order-management-service:
    image: wilbax/order-management:latest
    container_name: order-management-service
    networks:
      - private-network
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - service-registry

  payment-management-service:
    image: wilbax/payment-management:latest
    container_name: payment-management-service
    networks:
      - private-network
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - service-registry

networks:
  private-network:
    driver: bridge
  public-network:
    driver: bridge
